package by.epam.like_it.dao.criteria;


import by.epam.like_it.dao.ConcreteCriteria;
import by.epam.like_it.dao.Criteria;
import by.epam.like_it.model.Answer;

public enum AnswerCriteria implements ConcreteCriteria<Answer> {

    _$BANNED, _$CONTENT, _$CREATED_DATE, _$ID, _$POST_ID, _$UPDATED_DATE, _$USER_ID,

    COMMENTS$ANSWERS_ID, COMMENTS$BANNED, COMMENTS$CONTENT, COMMENTS$CREATED_DATE,
    COMMENTS$ID, COMMENTS$UPDATED_DATE, COMMENTS$USER_ID, POSTS$BANNED, POSTS$CATEGORY_ID,
    POSTS$CONTENT, POSTS$CREATED_DATE, POSTS$ID, POSTS$TITLE, POSTS$UPDATED_DATE,
    POSTS$USER_ID, RATING$ANSWER_ID, RATING$BANNED, RATING$CREATED_DATE, RATING$ID,
    RATING$RATING, RATING$UPDATED_DATE, RATING$USER_ID, USERS$BANNED, USERS$CREATED_DATE,
    USERS$EMAIL, USERS$FIRST_NAME, USERS$ID, USERS$LAST_NAME, USERS$LOGIN, USERS$PASSWORD,
    USERS$ROLE_ID, USERS$UPDATED_DATE, LIMIT


}
