package by.epam.like_it.dao.criteria;

import by.epam.like_it.dao.ConcreteCriteria;
import by.epam.like_it.model.User;


public enum UserCriteria implements ConcreteCriteria<User> {

    _$BANNED, _$CREATED_DATE, _$EMAIL, _$FIRST_NAME, _$ID,
    _$LAST_NAME, _$LOGIN, _$PASSWORD, _$ROLE_ID, _$UPDATED_DATE,

    ANSWERS$BANNED, ANSWERS$CONTENT, ANSWERS$CREATED_DATE,
    ANSWERS$ID, ANSWERS$POST_ID, ANSWERS$UPDATED_DATE, ANSWERS$USER_ID, COMMENTS$ANSWERS_ID,
    COMMENTS$BANNED, COMMENTS$CONTENT, COMMENTS$CREATED_DATE, COMMENTS$ID, COMMENTS$UPDATED_DATE,
    COMMENTS$USER_ID, FAVORITE_USERS_POSTS$COMMENT, FAVORITE_USERS_POSTS$ID,
    FAVORITE_USERS_POSTS$POST_ID, FAVORITE_USERS_POSTS$USER_ID, FAVORITE_USER_TAGS$TAGS_ID,
    FAVORITE_USER_TAGS$USER_ID, POSTS$BANNED, POSTS$CATEGORY_ID, POSTS$CONTENT,
    POSTS$CREATED_DATE, POSTS$ID, POSTS$TITLE, POSTS$UPDATED_DATE, POSTS$USER_ID,
    RATING$ANSWER_ID, RATING$BANNED, RATING$CREATED_DATE, RATING$ID, RATING$RATING, RATING$UPDATED_DATE,
    RATING$USER_ID, READED_POSTS$POST_ID, READED_POSTS$USER_ID, ROLES$ID, ROLES$NAME,
    LIMIT;

}
